apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.github-action-silent.triggered
      sendFinished: true
      requests:
        - "curl --header 'Authorization: token
          {{.env.secret_githubsecret_GITHUBTOKEN}}' --request POST --data
          '{\"event_type\":\"silent\",\"client_payload\":{\"type\":\"{{.type}}\
          \",\"project\":\"{{.data.project}}\",\"service\":\"{{.data.service}}\
          \",\"stage\":\"{{.data.stage}}\",\"shkeptncontext\":\"{{.shkeptnconte\
          xt}}\",\"id\":\"{{.id}}\"}}'
          https://api.github.com/repos/dt-alliances/ca-demo-github/dispatches"
      envFrom:
        - name: secret_githubsecret_GITHUBTOKEN
          secretRef:
            name: github-secret
            key: GITHUBTOKEN
      subscriptionID: 5eebbb8d-42eb-4d9c-9405-c3fe864289f6
