apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.github-action-interactive.triggered
      requests:
        - "curl --header 'Authorization: token
          {{.env.secret_githubsecret_GITHUBTOKEN}}' --request POST --data
          '{\"event_type\":\"interactive\",\"client_payload\":{\"type\":\"{{.ty\
          pe}}\",\"project\":\"{{.data.project}}\",\"service\":\"{{.data.servic\
          e}}\",\"stage\":\"{{.data.stage}}\",\"shkeptncontext\":\"{{.shkeptnco\
          ntext}}\",\"id\":\"{{.id}}\"}}'
          https://api.github.com/repos/dt-alliances/ca-demo-github/dispatches"
      envFrom:
        - name: secret_githubsecret_GITHUBTOKEN
          secretRef:
            name: github-secret
            key: GITHUBTOKEN
      subscriptionID: 867d0a56-69ef-4dde-87c3-264e81a14362
